force-app/main/default/objects/ContactChannel__c/ContactChannel__c.object-meta.xml
<CustomObject>
    <description
  >A contact&apos;s channel. Relates this person with an existing channel for communications.</description>
    <label>Contact Channel</label>
    <nameField>
        <label>Contact&apos;s Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Channels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactChannel__c/fields/ChannelRef__c.field-meta.xml
<CustomField>
    <fullName>ChannelRef__c</fullName>
    <label>Channel</label>
    <referenceTo>ConversationChannel__c</referenceTo>
    <relationshipLabel>Contact Channels</relationshipLabel>
    <relationshipName>ContactChannels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactChannel__c/fields/RelatedEntityRef__c.field-meta.xml
<CustomField>
    <fullName>RelatedEntityRef__c</fullName>
    <description
  >Field that stores the ID (as text) for another person entity, such as a Contact or Lead.</description>
    <label>Related Entity ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <label>Conversation</label>
    <nameField>
        <displayFormat>Conversation #{00000}</displayFormat>
        <label>Conversation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conversation__c/fields/ChannelRef__c.field-meta.xml
<CustomField>
    <fullName>ChannelRef__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>ConversationChannel__c</referenceTo>
    <relationshipLabel>Conversations</relationshipLabel>
    <relationshipName>Conversations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conversation__c/fields/ConversationId__c.field-meta.xml
<CustomField>
    <fullName>ConversationId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Message Bird Conversation ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Conversation__c/fields/RelatedEntityRef__c.field-meta.xml
<CustomField>
    <fullName>RelatedEntityRef__c</fullName>
    <externalId>true</externalId>
    <label>Related Entity ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Chat.cls
public without sharing class Chat {
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled(cacheable=true)
    public static List<ContactChannel__c> getAvailableChannels(Id recordId) {
        return [
            SELECT Id, Name, ChannelRef__c
            FROM ContactChannel__c
            WHERE RelatedEntityRef__c = :recordId
        ];
    }

    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled(cacheable=true)
    public static List<Conversation__c> getConversations(
        Id recordId,
        String channelId
    ) {
        try {
            return [
                SELECT Id, ConversationId__c, ChannelRef__c
                FROM Conversation__c
                WHERE
                    ChannelRef__c IN (
                        SELECT ChannelRef__c
                        FROM ContactChannel__c
                        WHERE RelatedEntityRef__c = :recordId
                    )
                    AND ConversationId__c != NULL
                    AND RelatedEntityRef__c = :recordId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static MessageBird.Result getMessages(String conversationId) {
        if (String.isBlank(conversationId)) {
            return null;
        }

        return MessageBird.getMessagesInConversation(
            new Map<String, Object>{ 'conversationId' => conversationId }
        );
    }

    @AuraEnabled
    public static MessageBird.Result replyConversation(
        Map<String, Object> params
    ) {
        try {
            Map<String, Object> apiParams = new Map<String, Object>{
                'type' => params.get('type'),
                'text' => params.get('content'),
                'conversationId' => params.get('conversationId')
            };
            return MessageBird.replyConversation(apiParams);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}