force-app/main/default/objects/ContactChannel__c/ContactChannel__c.object-meta.xml
<CustomObject>
    <description
  >A contact&apos;s channel. Relates this person with an existing channel for communications.</description>
    <label>Contact Channel</label>
    <nameField>
        <label>Contact&apos;s Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Channels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactChannel__c/fields/ChannelRef__c.field-meta.xml
<CustomField>
    <fullName>ChannelRef__c</fullName>
    <label>Channel</label>
    <referenceTo>ConversationChannel__c</referenceTo>
    <relationshipLabel>Contact Channels</relationshipLabel>
    <relationshipName>ContactChannels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConversationChannel__c/ConversationChannel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RecipientChannelHandler.cls
public inherited sharing class RecipientChannelHandler {
    public void run() {
        Set<Id> channelsIds = new Set<Id>();

        for (ContactChannel__c record : (List<ContactChannel__c>) Trigger.new) {
            channelsIds.add(record.ChannelRef__c);
        }

        Map<Id, ConversationChannel__c> channelsById = new Map<Id, ConversationChannel__c>(
            [
                SELECT Id, Name
                FROM ConversationChannel__c
                WHERE Id IN :channelsIds
            ]
        );

        for (ContactChannel__c record : (List<ContactChannel__c>) Trigger.new) {
            record.Name = channelsById.get(record.ChannelRef__c).Name;
        }
    }
}